# Generated by Django 4.1.5 on 2023-01-11 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1000)),
                ('company_type', models.CharField(max_length=1000)),
                ('counterparty_onboard_status', models.CharField(max_length=100)),
                ('counterparty_onboard_date', models.DateField()),
                ('buyer_supplier', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('insurance_bank', models.CharField(max_length=100)),
                ('receiving_bank', models.CharField(max_length=100)),
                ('tt_bank', models.CharField(max_length=100)),
                ('credit_amount', models.FloatField(blank=True, null=True)),
                ('credit_period', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('serenity_onboard_status', models.CharField(max_length=100)),
                ('serenity_onboard_date', models.DateField()),
                ('remarks', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000)),
                ('filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('uploaded_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanycreatedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_by', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('remark', models.CharField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.company')),
            ],
        ),
    ]
