# Generated by Django 4.1.5 on 2023-01-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_companyfile_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trader',
            field=models.CharField(default='Peter', max_length=1000),
        ),
    ]
