# Generated by Django 4.1.5 on 2023-01-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_company_trader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='trader',
            field=models.CharField(max_length=1000),
        ),
    ]
