# Generated by Django 4.1.5 on 2023-01-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_insurance_bank_receiving_bank_tt_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='counterparty_onboard_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='serenity_onboard_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
