# Generated by Django 4.1.5 on 2023-02-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_company_counterparty_onboard_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insurance_bank',
            new_name='Issuing_bank',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='insurance_bank',
            new_name='issuing_bank',
        ),
    ]
